image:
  file: .gitpod.Dockerfile

tasks:
  - init: sh ./.devcontainer/post-create.sh
    command: jekyll serve

ports:
  - port: 4000
    onOpen: open-browser
  - port: 35729
    onOpen: ignore

vscode:
  extensions:
    - kargware.vscode-extension-jekyll-kw
    - ginfuru.ginfuru-vscode-jekyll-syntax
    - znck.grammarly